"""Add S3 storage fields to reference_models

Revision ID: d5459f02bd62
Revises: 
Create Date: 2025-11-05 15:39:37.668620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5459f02bd62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_bucket', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('s3_prefix', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('storage_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_models', schema=None) as batch_op:
        batch_op.drop_column('storage_type')
        batch_op.drop_column('s3_prefix')
        batch_op.drop_column('s3_bucket')

    # ### end Alembic commands ###
